SET SCHEMA DB2INST1;

--homework
-- CHICAGO  -> HONG KONG
WITH PATH_TO(DEPARTURE, ARRIVAL, PRICE, FLIGHTS , TRAIN, LINKS)
AS
	(
	  SELECT DEPARTURE, ARRIVAL, PRICE, 1, 0, 0
	  FROM FLIGHTS
	  WHERE DEPARTURE = 'CHICAGO'
	  UNION ALL
	   SELECT DEPARTURE, ARRIVAL, PRICE, 0, 1, 0
	  FROM TRAINS
	  WHERE DEPARTURE = 'CHICAGO'
	  UNION ALL
	  SELECT C.DEPARTURE, C.ARRIVAL, (P.PRICE + C.PRICE), P.FLIGHTS + 1, P.TRAIN, P.LINKS + 1
	  FROM PATH_TO P, FLIGHTS C
	  WHERE P.ARRIVAL = C.DEPARTURE
	  UNION ALL
	  SELECT C.DEPARTURE, C.ARRIVAL, (P.PRICE + C.PRICE), P.FLIGHTS, P.TRAIN + 1, P.LINKS + 1
	  FROM PATH_TO P, TRAINS C
	  WHERE P.ARRIVAL = C.DEPARTURE
	)
SELECT ('CHICAGO - ' || ARRIVAL) AS PATH, LINKS, FLIGHTS , TRAIN, PRICE AS COST
FROM PATH_TO
WHERE ARRIVAL = 'HONG KONG' AND LINKS <= ALL (SELECT LINKS
											FROM PATH_TO WHERE ARRIVAL = 'HONG KONG')
--AND TRAIN != 0
GROUP BY ARRIVAL, LINKS, FLIGHTS , TRAIN, PRICE
--HAVING 
ORDER BY ARRIVAL, LINKS, FLIGHTS , TRAIN, PRICE;